pipeline {
  environment {
     antVersion = tool 'Ant1.10.8'
  }
  agent any
  stages {
    stage ('Initialize') {
      steps {
	        echo 'Placeholder.'
       		bat "echo testing"
       		bat "echo ${antVersion}"
      }
    }
  }
}