pipeline {
  environment {
     antVersion = tool 'Ant1.10.8'
  }
  agent any
  stages {
    stage ('Initialize') {
      steps {
	        echo 'Placeholder.'
       		bat "echo testing"
       		bat "${antVersion}\\bin\\ant -f Assignment4-Sieve-of-Erastosthenes\\build.xml clean"
      }
    }
  }
}