pipeline {
  environment {
     antVersion = tool 'Ant1.10.8'
  }
  agent any
  stages {
    stage ('Clean') {
      steps {
	        echo 'Clean.'
       		bat "${antVersion}\\bin\\ant -f Assignment4-Sieve-of-Erastosthenes\\build.xml clean"
      }
    }
    stage ('Initialize') {
      steps {
	        echo 'Initializing.'
       		bat "${antVersion}\\bin\\ant -f Assignment4-Sieve-of-Erastosthenes\\build.xml init"
      }
    }
    stage ('Compiling') {
      steps {
	        echo 'Compiling.'
       		bat "${antVersion}\\bin\\ant -f Assignment4-Sieve-of-Erastosthenes\\build.xml compile"
      } 
  	}
    stage ('Distribution') {
      steps {
	        echo 'Distribution.'
       		bat "${antVersion}\\bin\\ant -f Assignment4-Sieve-of-Erastosthenes\\build.xml dist"
      } 
  	}
    stage ('UnitTests') {
      steps {
	        echo 'UnitTests.'
       		bat "${antVersion}\\bin\\ant -f Assignment4-Sieve-of-Erastosthenes\\build.xml test"
      } 
  	}
  }
}